<style>
  .node {
    cursor: crosshair;
    stroke-width: 4;
  }

  .node_selected {
    stroke: #76d668;
  }

  .node_orphan {
    stroke: #f05a79;
  }

  .drag_line {
    stroke: #999;
    stroke-width: 5;
    pointer-events: none;
  }

  .drag_line_hidden {
    stroke: #999;
    stroke-width: 0;
    pointer-events: none;
  }

  .link {
    stroke: #0094a4;
    stroke-width: 3;
    stroke-dasharray: 2;
    cursor: crosshair;
  }

  .link_selected {
    stroke: #76d668;
  }

  .arrow {
    stroke: #0094a4;
    fill: #0094a4;
  }


  #hub-tooltip {
    border: 1px solid #c8dbde;
    background: #fff;
    padding: 4px;
    min-height: 1px;
    border-radius: 5px;
    color : #09bab4;
  }

  #hub {
    width: 100%;
  }

  #hub-tooltip span {
    display: inline-block;
  }
  #hub-tooltip label {
    float:left;
  }

  #svg-scale {
    position: absolute;
    margin-left: 5px;
    margin-top: 2px;
    background: #eee;
    padding: 2px;
    border-radius: 11px;
  }
</style>

<!-- shared bips container -->
<script id="tpl-shared-bips" type="text/template">
  <p class="lead middle">
    <img src="/static/img/curved-arrow-clip-art3.png" style="
    width: 70px;
    -webkit-transform: rotate(200deg);
    transform: rotate(200deg);
    ">
    create your own Bip or use one already shared
    <img src="/static/img/curved-arrow-clip-art3.png" style="
    width: 70px;
    -webkit-transform: rotate(15deg);transform: rotate(15deg);">

  <hr/>
</p>

<section class="ag-list">
  <div class="row" id="bips-list-shared"></div>
  <nav class="ag-list-pagination shared-list-pagination"></nav>
</section>
</script>

<!-- shared bip entity -->
<script id="tpl-shared-bip-entity" type="text/template">
  <div class="span8 shared-bip-container">
    <div class="row">
      <div class="bip-summary middle">
        <img class="tooltipped" data-placement="top" 
             title="<%=type_description %>" src="/static/img/channels/32/color/<%= type_icon %>" />
        <div class="shared-bip-list">
          <% var i = 0; _.each(normedManifest, function(manifest) { i++; %>
          <img class="mini tooltipped" data-placement="top" 
               title="<%= manifest.description + (manifest.description_long ? ' : ' + manifest.description_long : '') %>" 
               src="/static/img/channels/32/color/<%= manifest.pod %>.png"  />
          <% }); %>
        </div>
      </div>
      <div class="span5"">
        <div class="row">
          <div class="share-bip-description">
            <label class="">
              <%=name%>
            </label>
            <p><%= note %></p>
            <hr class="soften tight"/>
            <!-- div class="">
                via <img class="user-avatar mini" src="/static/img/cdn/av/<%=owner_id %>.jpg" alt="">
                  <a href="http://t.dev-local.bip.io"><%= owner_name %></a>
            </div -->
            <div class="">
              via <img class="user-avatar mini" src="/static/img/cdn/av/<%=owner_id %>.jpg" alt="">
              <%= owner_name %>
            </div>
          </div>
        </div>
      </div>
      <div class="share-controls">
        <button data-action="install" data-share-id="<%= id %>" class="btn btn-mini btn-success">Install</button>
        <% if (owner_id === __uid) { %>
        <button data-action="uninstall" data-share-id="<%= id %>" class="btn btn-mini btn-danger">Unshare</button>
        <% } %>
      </div>
    </div>

  </div>
</script>

<!-- shared bips setup (missing channels) -->
<script id="tpl-modal-share-setup" type="text/template">
  <div class="modal hide fade" role="dialog">
    <form id="share-form">
      <header class="modal-header candy-strip">
        <h2 class="">
          <i class="icon-exclamation-sign"></i> Activation Required For&nbsp;
        </h2>
        <% var i = 0; _.each(normedManifest, function(manifest) { i++; %>
        <img class="tooltipped mini" data-placement="top" title="<%= manifest.description + (manifest.description_long ? ' : ' + manifest.description_long : '') %>"  src="/static/img/channels/32/color/<%= manifest.pod %>.png"  />
        <% }); %>
      </header>
      <div class="modal-body middle candy-strip" id="share-setup-content">
        <p class="lead">
          <%= description %>
        </p>
        <hr/>
        <p>
          This shared bip contains channels which need extra setup from you prior to activation.
          You may be automatically redirected off-site to enable the BipIO App with a 3rd party provider, but don't worry, it will be quick.
          <br/><br/>
          <span class="alert alert-success">
            <i class="icon-thumbs-up"></i> Activating now will let you install similar bips in future, instantly.
          </span>
        </p>
      </div>
      <footer class="modal-footer">
        <div class="btn-row">
          <a class="btn modal-close" data-dismiss="modal" href="">Cancel</a>
          <a id="share-setup-action" class="btn btn-success modal-continue" href="">Next</a>
        </div>
      </footer>
    </form>
  </div>
</script>

<!-- action entity (dup from channel layout) -->
<script id="tpl-action-entity" type="text/template">
  <li class="action-selectable action <%= active_class %>">
    <input class="action-selected" type="radio" name="action" id="action" value="<%= name %>" <%= ('' != active_class ? 'checked' : '')%> />
           <h4><%= schema.description %> <span class="label action-type"><%= schema.trigger ? 'Emitter' : 'Action' %></span></h4>
    <p class="description"><%= schema.description_long %></p>

    <fieldset class="action-config">
      <% _.each(schema.config.properties, function(config, idx) { %>
      <div class="control-group">
        <label class="label control-label"><%= config.description %></label>
        <div class="controls">
          <span class="help-block"></span>
          <%= config._html %>
        </div>
      </div>
      <% });%>
    </fieldset>
  </li>
</script>

<!-- bip page layout -->
<script id="tpl-layouts-bips" type="text/template">
  <div id="manage-bips">
    <div class="row">
      <header class="span5">
        <h1 class="pull-left">Bips
          <small style="font-size:16.5px;">
            perform work with <a href="/dash#channels">channels</a> you've made
          </small>
        </h1>
      </header>
      <div class="span6 create-bip-buttons">
        <h2 class="pull-left">Create</h2>
        <a data-toggle="tooltip" data-title="Creates an Email Alias for your account domain" href="#bips/new/smtp" class="modal-trigger" data-bip-type="smtp" data-modal="#express-bip-email" href="">
          <img src="/static/img/channels/32/color/bip_smtp.png" /> Email Address
        </a>
        <a href="#bips/new/http" class="modal-trigger" data-bip-type="http" data-modal="#express-bip-http" href="">
          <img src="/static/img/channels/32/color/bip_http.png" /> Web Hook
        </a>
        <% if (emitters.length) { %>
        <a href="#bips/new/trigger" class="modal-trigger" data-bip-type="trigger" data-modal="#express-bip-trigger" href="">
          <img src="/static/img/channels/32/color/bip_trigger.png" /> Trigger
        </a>
        <% } %>

      </div>
    </div>
<hr/>
    <div class="row">
      <div class="span4">
        <section class="ag-list ag-list-bips">
          <form class="form-search">
            <input type="text" id="bip-search-form" placeholder="Search your bips..." />
            <button type="submit">
              <i class="icon-search"></i>
            </button>
          </form>

          <ul class="ag-list-results">
            <span class="list-widget" id="bip-list-widget"></span>
          </ul>

          <nav class="ag-list-pagination bip-list-pagination"></nav>
        </section>

      </div>
      <div class="span8" id="bip-setup"></div>

      <div id="hubModal"></div>
      <div id="emitterSelectModal"></div>
    </div>
  </div>
</script>

<!-- channel list entity (model view) copied from channel list templates -->
<script id="tpl-list-channel-entity" type="text/template">
  <li class="channel-list-item">
    <a href="#channels/<%= id %>" data-channel-id="<%= id %>">
      <strong class="name"><%= name %></strong>
      <small class="description"><%= note %></small>
      
      <% if (config.icon && '' !== config.icon) { %>
        <img src="<%= config.icon %>" alt="" class="hub-icon hub-icon-24" />
        <img style="top:auto; bottom: 1rem;" src="/static/img/channels/32/color/<%=pod%>.png" alt="" class="hub-icon hub-icon-24" />
      <% } else { %>            
        <img src="/static/img/channels/32/color/<%=pod%>.png" alt="" class="hub-icon hub-icon-24" />
      <% } %>
    </a>
  </li>
</script>

<!-- hub > channel vertex selection modal -->
<script id="tpl-modal-hub-channel-config" type="text/template">
  <div id="select-channel" class="modal-overlay hide">
    <div class="modal-container">
      <div class="modal modal-large modal-content select-channel-modal channel-settings-modal"></div>
    </div>
  </div>
</script>

<script id="tpl-modal-channel-select" type="text/template">
  <header class="modal-header candy-strip">
    <h2><%=modal_title%> <small>- <%=modal_subtitle%></small></h2>
  </header>

  <div class="modal-body candy-strip">    
    <section class="ag-list ag-list-horizontal ag-list-channels">
      <form class="form-search">
        <input id="channel-search-form" type="text" class="search-query" placeholder="Search your channels..." />
        <button type="submit"><i class="icon-search"></i></button>
        <p class="hint"><strong>Hint:</strong> Try searching by service, such as “Dropbox” or “Facebook”.</p>
      </form>
      <ul class="ag-list-results"></ul>
      <nav class="ag-list-pagination channel-list-pagination"></nav>
    </section>
  </div>
  <footer class="modal-footer">
    <div class="btn-row">
        <!-- a class="btn modal-confirm btn-success <%= (selected ? '' : 'disabled') %>" href="">Continue</a -->
      <a class="btn modal-close" data-dismiss="modal" aria-hidden="true">Cancel</a>
    </div>
  </footer>
</script>


<script id="tpl-modal-hub-transform-config" type="text/template">
  <header class="modal-header candy-strip">
    <h2>Message Transforms: <img src="/static/img/channels/32/color/<%= action.split('.')[0] %>.png" alt="" class="hub-icon hub-icon-32" /> <%= name %></h2>
  </header>
  <div class="modal-body candy-strip">
    <p>
    <div class="alert alert-warning middle">
      '<%= _repr %>' can be templated as you like, so just start typing.<br/>  To map
      the attributes of channels as part of your template, press Ctrl+i in-place to
      make a selection
    </div>
  </p>
  <form class="form-horizontal" id="panel-channel-transform-body">
  </form>
</div>
<footer class="modal-footer">
  <div class="btn-row">
    <a class="btn btn-success modal-confirm" href="">Save Action</a>
    <a class="btn modal-close" data-dismiss="modal" aria-hidden="true">Cancel</a>

    <a class="btn btn-text pull-right btn-reselect" href="">Choose a different channel</a>
  </div>
</footer>
</script>

<script id="tpl-modal-hub-channel-transform" type="text/template">
  <div class="control-group">
    <label class="control-label" for="import-<%=name%>"><%=description%></label>
    <div class="controls">
        <!-- input type="text" id="import-<%=name%>" -->
      <div id="import-<%=name%>" class="templar field"></div>
    </div>
  </div>
</script>

<!-- bip list container -->
<script id="tpl-resource-list-bip" type="text/template">
  <header class="header-bip"></header>

  <div id="list-bip-container">
    <ul id="bip-list" class="ag-list-results list-bips"></ul>
    <footer>
      <nav id="bip-list-pagination" class="pagination">
      </nav>
    </footer>
  </div>
</script>

<!-- bip select -->
<script id="tpl-bip-select" type="text/template">

  <form id="create-new-bip-1" class="create-new create-new-bip">
    <h2><img src="/static/img/channels/32/color/bip_<%= type%>.png" alt="" class="hub-icon hub-icon-24"/>
      <% if (shared) { %>
        Confirming Setup for
      <% } else if (isNew) { %>Creating <% } else { %>Updating <% } %> <%= _label %>
    </h2>
    <hr class="soften"/>

    <% if (!isNew) { %>

      <div class="bip-save-required alert alert-warning hide">
        <i class="icon-warning-sign"></i> <strong>Save Required</strong>
      </div>

      <ul class="nav nav-tabs" id="bip-config-tabs">
        <div class="btn-group pull-right">
          <% if ('trigger' !== type) { %>
            <button  type="button" data-action="dup" class="btn btn-small btn-info dup-action"><i class="icon-copy"></i> Copy</button>
          <% } %>
          <button  type="button" data-action="share" class="btn btn-small btn-info share-action"><i class="icon-share"></i> Share Config</button>
          <% if (paused) { %>
          <button  type="button" data-action="play" class="btn btn-small btn-danger pause-action"><i class="icon-play"></i> Unpause</button>
          <% } else { %>
          <button  type="button" data-action="paused" class="btn btn-small btn-success pause-action"><i class="icon-pause"></i> Pause Now</button>
          <% } %>
        </div>
        <li class="active" ><a data-toggle="pill" href="#bip-config-panel"> <i class="icon-cogs"></i> Setup</a></li>

        <% if ('http' === type) { %>
        <li><a data-toggle="pill" href="#bip-render-panel"><i class="icon-eye-open"></i> Renderer</a></li>
        <% } %>

        <% if (false && 'trigger' !== type) { %>
        <li><a data-toggle="pill" href="#bip-binder-panel"><i class="icon-link"></i> Bindings</a></li>
        <% } %>

        <li><a data-toggle="pill" href="#bip-data-panel"><i class="icon-wrench"></i> Data View</a></li>
        <li><a data-toggle="pill" href="#bip-logs-panel"><i class="icon-tasks"></i> Logs</a></li>
      </ul>

      <div class="tab-content no-overflow">
        <div class="tab-pane active" id="bip-config-panel">
  <% } %>

        <% if (type == 'trigger') { %>
        <input type="hidden" id="bip_channel_id" value="<%= config.channel_id %>"/>
          <% if (!isNewTrigger) { %>
          <div class="create-new-channel">
            <header>
              <h2>
                <img src="/static/img/channels/32/color/<%= pod.name %>.png" alt="" class="hub-icon hub-icon-32" />
                <%= trigger.name %>
              </h2>
              <p class="alert alert-info">
                <%= trigger.note %> (<%= pod.description %>)
              </p>
            </header>
          </div>
          <% } %>
        <% } %>

        <div id="bip-config" class="fade <%= (type == 'trigger' && isNewTrigger && !shared ? 'out' : 'in')%>">
          <% if (app_id) {%>
            <small class="pull-right">via <%=app_id%></small>
          <% } %>
          <fieldset class="basic-info">
            <div class="control-group">
              <div>
                <label class="control-label" for="bip_name">Name</label>
              </div>
              <div class="controls">
                <% if (type == 'smtp') { %>
                <input type="text" id="bip_name" placeholder="bip name, alphanumeric only" value="<%= name %>">
                @
                <select id="domain_id">
                  <% _(domainCollection).each(function(domain) { %>
                  <% if (domain._available ) { %>
                  <option value="<%= domain.id %>" <% if (domain.id == domain_id) { %> selected="selected" <% } %> ><%= domain.name %></option>
                  <% } %>
                  <% }); %>
                </select>
                <% } else if (type == 'http') { %>
                <select id="domain_id">
                  <% _(domainCollection).each(function(domain) { %>
                  <% if (domain._available ) { %>
                  <option value="<%= domain.id %>" <% if (domain.id == domain_id) { %> selected="selected" <% } %> ><%= domain.name %></option>
                  <% } %>
                  <% }); %>
                </select>
                /bip/http/
                <input class="input-xlarge" type="text" id="bip_name" placeholder="bip name, alphanumeric only" value="<%= name %>">
                <% } else { %>
                <input class="input-xlarge" type="text" id="bip_name" placeholder="bip name, alphanumeric only" value="<%= name %>">
                <% } %>
                <span class="help-block"></span>
              </div>

              <% if (type !== 'trigger') { %>
              <div id="bip-repr" class="">
                <label>Endpoint </label>
                <div id="bip-repr-actual" class=" alert alert-info" data-toggle="tooltip" title="Click To Select" >
                  <%= _repr || 'none' %>
                </div>
              </div>
              <% } %>

            </div>

            <div class="control-group">
              <label class="control-label" for="node">Description</label>
              <div class="controls">
                <textarea type="text" id="bip_note" placeholder="short description"><%= note %></textarea>
                <span class="help-block"></span>
              </div>
            </div>

            <% if (type == 'http') { %>

            <div class="control-group">
              <label class="control-label" for="auth">Authentication</label>
              <div class="controls">
                <select id="auth">
                  <option value="none" <%=(config.auth === 'none') ? 'selected="selected"' : ''%>>None</option>
                  <option value="token" <%=(config.auth === 'token' || !config.auth) ? 'selected="selected"' : ''%>>Use My API Token</option>
                  <option value="basic" <%=(config.auth === 'basic') ? 'selected="selected"' : ''%>>Basic</option>
                </select>
                <!-- i class=" icon-question-sign" data-toggle="popover" data-placement="right" data-content="" title="HTTP Authentication"></i -->
                <span class="help-block"></span>
              </div>

              <div class="control-group" id="auth-control" style="<%=(config.auth === 'basic') ? '' : 'display:none'%>">
                <label class="control-label" for="auth">Username</label>
                <div class="controls">
                  <input id="auth_username" type="text" value="<%=config.username%>" />
                </div>
                <label class="control-label" for="auth">Password</label>
                <div class="controls">
                  <input id="auth_password" type="text" value="<%=config.password%>" />
                </div>
              </div>
            </div>

            <% } %>

            <hr class="soften" />

            <div class="control-group expiration">
              <input type="hidden" id="bip_end_life" />
              <span class="help-block"></span>

              <label class="control-label">Expiry</label>

              <% if (isNew && !explicitDate) { %>
              <div class="controls">
                <div class="input-prepend">
                  <span class="add-on tooltipped" data-toggle="tooltip" data-title="After Date"><i class="icon-time"></i></span>
                  <input id="bip_expiry_time" id="appendedPrependedInput"  type="text" value="<%= expiry_time %>" placeholder="Never">
                  <select class="input-small" id="bip_expiry_time_resolution">
                    <option value="hour" <% if (expiry_time_period == 'h') { %> selected="selected" <% } %> >Hours</option>
                    <option value="day" <% if (expiry_time_period == 'd') { %> selected="selected" <% } %>>Days</option>
                    <option value="month" <% if (expiry_time_period == 'm') { %> selected="selected" <% } %>>Months</option>
                    <option value="year" <% if (expiry_time_period == 'y') { %> selected="selected" <% } %>>Years</option>
                  </select>
                </div>
              </div>
              <% } else { %>
              <div class="controls datepicker-input">
                <div class="input-prepend">
                  <span class="add-on tooltipped" data-toggle="tooltip" data-title="After Date"><i class="icon-time"></i></span>
                  <input type="text" class="input-large date" name="expire-date"
                         data-date-format="mm/dd/yy"
                         id="bip_expiry_date"
                         placeholder="<%= (expiry_time ? '' : 'Never') %>"
                         value="<%= expiry_time ? expiry_time : ''  %>"
                         /><%= time_zone %>
                </div>
              </div>
              <% } %>

              <div class="controls">
                <div class="input-prepend">
                  <span class="add-on tooltipped" data-toggle="tooltip" data-title="# Impressions">
                    <i class="icon-heart"></i>
                    <% if (!isNew && expiry_imp) { %>
                    <%= _imp_actual %> /
                    <% } %>
                  </span>
                  <input type="text" name="expire-imp"
                         id="bip_expiry_imp"
                         placeholder="<%= (expiry_imp ? '' : 'Never') %>"
                         value="<%= expiry_imp ? expiry_imp : ''  %>"
                         />
                </div>
              </div>


              <div class="controls pull-right">
                  <div class="btn-group" data-toggle="buttons-radio" id="bip_expire_behaviour">
                      <button type="button" data-selection="pause" class="btn btn-info <% if (end_life.action == 'pause') { %>active<% } %>"><i class="icon-pause"></i> Pause</button>
                      <button type="button" data-selection="delete" class="btn btn-info <% if (end_life.action == 'delete') { %>active<% } %>"><i class="icon-ban-circle"></i> Delete</button>
                  </div>
              </div>
            </div>

          </fieldset>
          <fieldset class="map-action">
            <h3>
              Hub <small>- message transform</small>
              <small class="pull-right">
                <label data-toggle="popover" data-title="<i class='icon-exclamation-sign'></i> Instructions" data-html="true" data-placement="top" data-trigger="click" data-content="
                       <strong>Drag</strong> from the Bip source or an existing Channel to create a link to a new Channel.<br/><br/>
                       <strong>Clic</strong>k to (de)select Channels or Links.<br/><br/>
                       <strong>Double-Click</strong> an icon to configure a Channel
                       <br/><br/>
                       The <strong>[DELETE]</strong> key removes the selected Channel or link.
                       <br/><br/>
                       <strong>Drag</strong> with your mouse to pan.<br/><br/>
                       <strong>Scroll</strong> your mouse to zoom.
                       " class="label label-success">
                  <i class="icon-question-sign"></i> Instructions
                </label>
              </small>
            </h3>

            <div class="control-group">
              <div class="controls">
                <span class="help-block"></span>
              </div>
            </div>
            <div id="hub">
              <!-- div id="hub-legend" class="pull-right" style="display:inline-block;">
                  <strong>legend</strong>
                  <div style="width:24px;height:24px;border-radius:50%;border: 3px solid #94c83d ">
                  </div>
              </div -->

              <div id="svg-scale">100%</div>
              <input id="hub-focus"/>

            </div>
            <% if (type !== 'trigger') { %>
            <!-- div class="control-group">
                <div class="controls">
                    <label class="control-label">Express Setup</label>
                    <label class="checkbox">
                        <input id="bip_default" type="checkbox"> Use this configuration for express setup
                    </label>
                </div>
            </div -->
            <% } %>
          </fieldset>
          <div class="form-actions">
            <button id="bip-submit" type="submit" class="btn btn-success"><%= (isNew) ? 'Create' : 'Save' %> <%= _label %></button>
            <button id="bip-cancel" type="button" class="btn"><%= (isNew) ? 'Cancel' : 'Close' %></button>
            <% if (!isNew) { %>
            <a href="#/bips/<%= id %>/delete" class="danger-link pull-right"><i class="icon-ban-circle"></i> Delete this bip</a>
            <p class="note">Any changes made to this bip will take effect immediately upon saving.</p>
            <% } %>
          </div>
        </div>

        <% if (!isNew) { %>
      </div>

      <div class="tab-pane" id="bip-logs-panel">
        <table class="table table-condensed table-striped">
          <thead>
            <tr>
              <th>Date</th>
              <th>Code</th>
              <th>Message</th>
            </tr>
          </thead>
          <tbody id="log-body"></tbody>
        </table>
      </div>

      <div class="tab-pane" id="bip-data-panel">
        <p class="lead">Raw JSON Config</p>
        <pre class="prettyprint">
        </pre>
      </div>

      <div class="tab-pane" id="bip-binder-panel">
        <p class="lead">Control who can send messages to this Bip</p>
        <ul class="link-list">
          <li>
            <input type="radio" /> Bind to First Connecting Client
          </li>
          <li>
            or <input type="text" placeholder="IPv4 or IPv6 <%=(type === 'smtp' ? 'or Email Address' : '')%>" />
            <button class="btn btn-success pull-right">Add</button>
          </li>
        </ul>

      </div>

      <div class="tab-pane" id="bip-render-panel">
        <p class="lead">Web Hook Renderers serve channel content whenever they are called</p>
        <ul class="link-list">
          <li class="renderer-selected">
          </li>
        </ul>
        <h3>Select : </h3>
        <ul class="link-list renderer-container">
          <% _.each(rendererChannels, function(channel) { %>
          <div class="create-new-channel select-renderer">
            <header>
              <h5>
              <img class="hub-icon hub-icon-24" src="/static/img/channels/32/color/<%= channel.pod.name %>.png">
              <%= channel.pod.description + ' : ' + channel.name%>
              </h5>

              <% _.each(channel._renderers, function(r, idx) { %>
                <li data-link="<%= r._href %>" data-channel-id="<%= channel.id%>" data-renderer="<%= idx %>">
                  <%=r.description%> (<%=r.contentType%>)
                  <button class="btn btn-mini btn-success btn-enable-renderer pull-right">Enable</button>
                  <button class="btn btn-mini pull-right btn-preview-renderer">Preview</button>
                  <span class="pull-right"><%=r.description_long%></span>
                </li>
              <% }); %>
              </header>
          </div>
          <% }); %>
        </ul>
      </div>

    </div>
    <% } %>
  </form>

</script>

<div id="sharedModal"></div>